baseURL = 'https://lottie4j.com/'
languageCode = 'en-us'
title = 'Lottie4J'
theme = 'hugo-theme-relearn'

[markup.goldmark.renderer]
unsafe = true

[params]
themeVariant = 'zen-light'
editURL = 'https://github.com/lottie4j/lottie4j-website/edit/main/content/'